import 'dart:io';

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:mailer/mailer.dart';
import 'package:mailer/smtp_server/gmail.dart';
import 'package:pim/components/custom_surfix_icon.dart';
import 'package:pim/components/default_button.dart';
import 'package:pim/components/form_error.dart';
import 'package:pim/module/services.dart';
import 'package:pim/screens/complete_profile/complete_profile_screen.dart';
import 'package:pim/otp/otp_screen.dart';
import 'package:pim/screens/sign_in/components/custom_dialog.dart';

import 'package:shared_preferences/shared_preferences.dart';
import '../../../constants.dart';
import '../../../size_config.dart';

class SignUpForm extends StatefulWidget {
  @override
  _SignUpFormState createState() => _SignUpFormState();
}

class _SignUpFormState extends State<SignUpForm> {
  SharedPreferences preferences;
  final _formKey = GlobalKey<FormState>();
  String email;
  String password;
  String conform_password;
  bool remember = false;
  final List<String> errors = [];

  void addError({String error}) {
    if (!errors.contains(error))
      setState(() {
        errors.add(error);
      });
  }

  void removeError({String error}) {
    if (errors.contains(error))
      setState(() {
        errors.remove(error);
      });
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        children: [
          buildEmailFormField(),
          SizedBox(height: getProportionateScreenHeight(30)),
          buildPasswordFormField(),
          SizedBox(height: getProportionateScreenHeight(30)),
          buildConformPassFormField(),
          FormError(errors: errors),
          SizedBox(height: getProportionateScreenHeight(40)),
          DefaultButton(
            text: tr("Continue"),
            press: () {
              if (_formKey.currentState.validate()) {
                _formKey.currentState.save();
                // if all are valid then go to success screen
                service().registerUserBusiness(email, password).then((newSms) async {
                  if (newSms.statusCode == 409) {
                    showDialog(
                      context: context,
                      builder: (BuildContext context) => CustomDialog(
                        title: tr("sign up failed"),
                        description: tr("email is already used"),
                        primaryButtonText: tr("bouttondialog"),
                      ),
                    );
                  } else {
                    preferences = await SharedPreferences.getInstance();

                    await preferences.setString('email', email);
                    print("waaaaaa");
                    print(newSms.body);
                    sendmail(newSms.body, email);
                    Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => OtpScreen(
                                  email: email,
                                )));
                  }
                });
              }
            },
          ),
        ],
      ),
    );
  }

  sendmail(String verificationcode, String email) async {
    String username = 'youssef.benhissi@esprit.tn';
    String password = 'ilovetennis';

    final smtpServer = gmail(username, password);
    // Use the SmtpServer class to configure an SMTP server:
    // final smtpServer = SmtpServer('smtp.domain.com');
    // See the named arguments of SmtpServer for further configuration
    // options.

    // Create our message.
    var yourHtmlTemplate =
        '''<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!-- Automatically generated by make_email v0.8.0. Do not edit this file. -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta name="x-apple-disable-message-reformatting" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="https://growth.lyft.com.s3.amazonaws.com/lyft%20favicon.ico" type="image/gif" sizes="32x32">
  <title>Lyft</title>
  <style type="text/css">
    /*******************FONT STYLING LYFT*********************/

    @import url(http://lyft-assets.s3.amazonaws.com/font/Lyft%20Pro/LyftPro-Bold.otf);
    @font-face {
      font-family: 'LyftPro-Bold';
      src: url(https://lyft-assets.s3.amazonaws.com/font/Lyft%20Pro/LyftPro-Bold.otf) format("opentype");
      font-weight: bold;
      font-style: normal;
    }

    @import url(http://lyft-assets.s3.amazonaws.com/font/Lyft%20Pro/LyftPro-Regular.otf);
    @font-face {
      font-family: 'LyftPro-Regular';
      src: url(https://lyft-assets.s3.amazonaws.com/font/Lyft%20Pro/LyftPro-Regular.otf) format("opentype");
      font-weight: normal;
      font-style: normal;
    }

    @import url(https://lyft-assets.s3.amazonaws.com/font/Lyft%20Pro/LyftPro-SemiBold.otf);
    @font-face {
      font-family: 'LyftPro-SemiBold';
      src: url(https://lyft-assets.s3.amazonaws.com/font/Lyft%20Pro/LyftPro-SemiBold.otf) format("opentype");
      font-weight: normal;
      font-style: normal;
    }


    /************************* END FONT STYLING ************************************/

    body {
      width: 100%;
      background-color: #FFFFFF;
      margin: 0;
      padding: 0;
      -webkit-font-smoothing: antialiased;
      font-family: 'Open Sans', Arial, sans-serif;
    }

    table {
      border-collapse: collapse;
    }

    img {
      border: 0;
      outline: none !important;
    }

    .hideDesktop {
      display: none;
    }

    /********* CTA Style - fixed padding *********/

    .cta-shadow {
      padding: 14px 35px;
      -webkit-box-shadow: 0px 5px 0px rgba(0, 0, 0, 0.2);
      -moz-box-shadow: 0px 5px 0px rgba(0, 0, 0, 0.2);
      box-shadow: 0px 5px 0px rgba(0, 0, 0, 0.2);
      -moz-border-radius: 25px;
      -webkit-border-radius: 25px;
      font-size: 16px;
      font-weight: normal;
      letter-spacing: 0px;
      text-decoration: none;
      display: block;
    }

    body[yahoo] .hideDeviceDesktop {
      display: none;
    }

    @media only screen and (max-width: 640px) {

      div[class=mobilecontent] {
        display: block !important;
        max-height: none !important;
      }

      body[yahoo] .fullScreen {
        width: 100% !important;
        padding: 0px;
        height: auto;
      }

      body[yahoo] .halfScreen {
        width: 50% !important;
        padding: 0px;
        height: auto;
      }

      body[yahoo] .mobileView {
        width: 100% !important;
        padding: 0 4px;
        height: auto;
      }

      body[yahoo] .center {
        text-align: center !important;
        height: auto;
      }

      body[yahoo] .hideDevice {
        display: none;
      }

      body[yahoo] .hideDevice640 {
        display: none;
      }

      body[yahoo] .showDevice {
        display: table-cell !important;
      }

      body[yahoo] .showDevice640 {
        display: table !important;
      }


      body[yahoo] .googleCenter {
        margin: 0 auto;
      }

      .mobile-LR-padding-reset {
        padding-left: 0 !important;
        padding-right: 0 !important;
      }
      .side-padding-mobile {
        padding-left: 40px;
        padding-right: 40px;
      }
      .RF-padding-mobile {
        padding-top: 0 !important;
        padding-bottom: 25px !important;
      }
      .wrapper {
        width: 100% !important;
      }
      .two-col-above {
        display: table-header-group;
      }
      .two-col-below {
        display: table-footer-group;
      }
      .hideDesktop {
        display: block !important;
      }
    }

    @media only screen and (max-width: 520px) {
      .mobileHeader {
        font-size: 50px !important;
      }
      .mobileBody {
        font-size: 16px !important;
      }
      .mobileSubheader {
        font-size: 30px !important;
      }
    }

    @media only screen and (max-width: 479px) {

      body[yahoo] .fullScreen {
        width: 100% !important;
        padding: 0px;
        height: auto;
      }

      body[yahoo] .mobileView {
        width: 100% !important;
        padding: 0 4px;
        height: auto;
      }

      body[yahoo] .center {
        text-align: center !important;
        height: auto;
      }

      body[yahoo] .hideDevice {
        display: none;
      }

      body[yahoo] .hideDevice479 {
        display: none;
      }

      body[yahoo] .showDevice {
        display: table-cell !important;
      }

      body[yahoo] .showDevice479 {
        display: table !important;
      }

      .mobile-LR-padding-reset {
        padding-left: 0 !important;
        padding-right: 0 !important;
      }
      .side-padding-mobile {
        padding-left: 40px;
        padding-right: 40px;
      }
      .RF-padding-mobile {
        padding-top: 0 !important;
        padding-bottom: 25px !important;
      }
      .wrapper {
        width: 100% !important;
      }
      .two-col-above {
        display: table-header-group;
      }
      .two-col-below {
        display: table-footer-group;
      }
      .mobileButton {
        width: 150px !important !
      }

    }

    @media only screen and (max-width: 385px) {
      .mobileHeaderSmall {
        font-size: 18px !important;
        padding-right: none;
      }
      .mobileBodySmall {
        font-size: 14px !important;
        padding-right: none;
      }
    }

    /* Stops automatic email inks in iOS */

    a[x-apple-data-detectors] {

      color: inherit !important;

      text-decoration: none !important;

      font-size: inherit !important;

      font-family: inherit !important;

      font-weight: inherit !important;

      line-height: inherit !important;

    }

    a[href^="x-apple-data-detectors:"] {
      color: inherit;
      text-decoration: inherit;
    }

    .footerLinks {
      text-decoration: none;
      color: #384049;
      font-family: 'LyftPro-Regular', 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 12px;
      line-height: 18px;
      font-weight: normal;
    }

    /*******Some Clients do not support rounded borders (example: older versions of Outlook)**********/

    .roundButton {
      border-radius: 5px;
    }

    /************************* Fixing Auto Styling for Gmail*********************/

    .contact a {
      color: #88888f !important !;
      text-decoration: none;
    }

    u+#body a {
      color: inherit;
      text-decoration: none;
      font-size: inherit;
      font-family: inherit;
      font-weight: inherit;
      line-height: inherit;
    }
  </style>
  <!-- Fall-back font for Outlook (Arial) -->
  <!--[if (gte mso 9)|(IE)]>

    <style type="text/css">

    a, body, div, li, p, strong, td, span {font-family: Arial, Helvetica, sans-serif !important;}
    
    </style>

  <![endif]-->
</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" yahoo="fix" style="font-family: 'Open Sans', Arial, sans-serif;" align="center" id="body">
  <custom type="content" name="ampscript">
    <!-- FULL PAGE WIDTH WRAPPER WITH TINT -->
    <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td align="center" bgcolor="#f3f3f5" valign="top" width="100%">
          <!--========= WHITE PAGE BODY CONTAINER/WRAPPER========-->
          <table align="center" border="0" cellpadding="0" cellspacing="0" class="mobileView" width="600" style="">
            <tr>
              <td align="center" bgcolor="#FFFFFF" style="padding:0px;" width="100%">

                <!--================================SECTION 0==========================-->
                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;background-color:#625a9c;" width="600">
                  <tr>
                    <td bgcolor="#FFD6E5" class="" style="width:100% !important; padding: 0;background-color:#ffffff;">
                      <!--========Paste your Content below=================-->
                      <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
                        <tr>
                          <td class="divider" align="center" height="16px" style="background-color: #F3F3F5;">
                          </td>
                        </tr>
                      </table>
                      <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
                        <tr>
                          <td align="center" height="25px" style="background-color: #FFFFFF;">
                          </td>
                        </tr>
                      </table>
                      <!-- BEGIN LOGO -->
                      <table cellspacing="0" cellpadding="0" align="left" border="0" width="100%" bgcolor="#ffffff">
                        <tr>
                          <td valign="top" align="left" width="100%" style="padding-left: 25px;">
                            <img style="max-width: 150px; height: auto" src="https://s3.amazonaws.com/growth.lyft.com/Business/Logos/Business_LogoPink%402x.png" alt="Lyft for Business" />
                          </td>
                        </tr>
                      </table>
                      <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
                        <tr>
                          <td align="center" height="25px" style="background-color: #FFFFFF;">
                          </td>
                        </tr>
                      </table>
                      <!-- END LOGO -->

                      <!-- nothing -->

                      <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>
                <!--=======END SECTION==========-->

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <custom type="content" name="hero_image">
                        <!--========Paste your Content below=================-->

                        <!-- nothing -->

                        <!--BEGIN HERO IMAGE -->
                        <table cellspacing="0" cellpadding="0" align="left" border="0" width="100%" bgcolor="#ffffff">
                          <tr>
                            <td valign="top" align="center" width="100%" style="padding-right: 25px; padding-left: 25px;">
                              <img width="100%" style="max-width: 600px; height: auto" src="https://s3.amazonaws.com/growth.lyft.com/Business/Images/Hero%20Images/Verifyemail_hero%402x.png" alt="Lyft business profile" />
                            </td>
                          </tr>
                        </table>
                        <!--END HERO IMAGE-->

                        <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
                          <tr>
                            <td align="center" height="25px" style="background-color: #FFFFFF;">
                            </td>
                          </tr>
                        </table>

                        <!--BEGIN TEXT SECTION-->
                        <table width="100%" align="center" cellpadding="0" cellspacing="0" border="0" style="max-width: 600px;">
                          <tr>
                            <td style="font-family: 'LyftPro-Bold', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 1.0; color: #000000; font-weight: bolder; text-transform: uppercase; padding: 25px 25px 5px 25px;" class="mso-line-solid">
                              YOU'RE ONE STEP AWAY
                            </td>
                          </tr>
                          <tr>
                            <td style="font-family: 'LyftPro-Bold', Arial, Helvetica, sans-serif; font-size: 52px; line-height: 1.0; color: #000000; font-weight: bolder; padding: 0 25px 15px 25px;" class="mso-line-solid mobile-headline">
                              Verify your email address
                            </td>
                          </tr>
                          <tr>
                            <td style="font-family: 'LyftPro-Regular', Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.4; color: #000000; padding: 0 25px 50px 25px;">
                              To complete your profile and start taking business rides with Lyft, you'll need to verify your email address.
                            </td>
                          </tr>

                          <!-- CTA -->
                           <div style="background-color:transparent;">
              <div style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;" class="block-grid ">
                <div style="border-collapse: collapse;display: table;width: 100%;background-color:transparent;">

                  <!--[if (mso)|(IE)]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="background-color:transparent;" align="center"><table cellpadding="0" cellspacing="0" border="0" style="width: 500px;"><tr class="layout-full-width" style="background-color:transparent;"><![endif]-->

                  <!--[if (mso)|(IE)]><td align="center" width="500" style=" width:500px; padding-right: 0px; padding-left: 0px; padding-top:5px; padding-bottom:0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent;" valign="top"><![endif]-->
                  <div class="col num12" style="min-width: 320px;max-width: 500px;display: table-cell;vertical-align: top;">
                    <div style="background-color: transparent; width: 100% !important;">

                      <!--[if (!mso)&(!IE)]>
<!-->
                      <div style="border-top: 0px solid transparent; border-left: 0px solid transparent; border-bottom: 0px solid transparent; border-right: 0px solid transparent; padding-top:5px; padding-bottom:0px; padding-right: 0px; padding-left: 0px;">

                        <!--<![endif]-->
                        <div class="button-container left">

                          <!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tr><td style="padding:0px; margin:0px;text-align:center;" align="center"><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="" style="height:66pt; v-text-anchor:middle; width:350pt;" arcsize="5%" strokecolor="#E0E0E0" fillcolor="#ffffff"><w:anchorlock/><v:textbox inset="0,0,0,0"><center style="color:#000000; font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size:55px;"><![endif]-->
                          <div style="color: #000000; background-color: #fff; margin: 0; border-radius: 5px; -webkit-border-radius: 5px; -moz-border-radius: 5px; max-width: 100%; width: 100%; border-radius: 12px; border: 1px solid rgba(0,0,0,0.12); padding: 10px 0; font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; text-align: center; mso-border-alt: none;">
                            <span style="font-family:monospace, Arial, 'Helvetica Neue', Helvetica, sans-serif;font-size:16px;"><span style="font-size: 43px; line-height: 55px; letter-spacing: 20px; display: inline-block; margin-left: 20px">{{VERIFICATIONCODE}}</span></span>
                          </div>

                          <!--[if mso]></center></v:textbox></v:roundrect></td></tr></table><![endif]-->
                        </div>
                        <div class="">

                          <!--[if mso]><table width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="padding:10px 0;"><![endif]-->
                          <div style="color:#000000;font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif;line-height:120%; padding: 0px;">
                            <div style="font-size:12px;line-height:24px;color:#000000;font-family:Arial, 'Helvetica Neue', Helvetica, sans-serif;text-align:left;">
                              <p style="margin: 0;font-size: 14px;line-height: 24px;text-align: center">Please note this code is only valid for 15 minutes.</p>
                              <p style="margin: 0;font-size: 64px;line-height: 64px;text-align: left">&#160;</p>
                              <p style="margin: 0;font-size: 24px;line-height: 32px;text-align: left">Have questions or trouble logging in?</p>
                              <p style="margin: 0;font-size: 18px;line-height: 18px;text-align: left">&#160;</p>
                              <p style="margin: 0;font-size: 18px;line-height: 26px;text-align: left">Just reply to this email or contact <a href="mailto:support@whereby.com" style="color: #2b189b">support@whereby.com</a></p>
                              <p style="margin: 0;font-size: 100px;line-height: 100px;text-align: left">&#160;</p>
                              <p style="margin: 0 0 40px 0; font-size: 18px;line-height: 26px;text-align: center">
                                <a href="https://whereby.com/" target="_blank" style="display: inline-block; margin: 20px 0;">
                                  <img class="center autowidth" align="center" border="0" style="display: block; text-align: center;" alt="All the best, The Whereby team" title="Whereby logo" src="https://i.imgur.com/w7J7QN5.png" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: block !important;border: 0;height: auto;float: none" width="auto" />
                                </a>
                              </p>
                            </div>
                          </div>

                          <!--[if mso]></td></tr></table><![endif]-->
                        </div>

                        <!--[if (!mso)&(!IE)]>
<!-->
                      </div>

                      <!--<![endif]-->
                    </div>
                  </div>

                  <!--[if (mso)|(IE)]></td></tr></table></td></tr></table><![endif]-->
                </div>
              </div>
            </div>
                        </table>

                        <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
                          <tr>
                            <td align="center" height="25px" style="background-color: #FFFFFF;">
                            </td>
                          </tr>
                        </table>
                        <!--END TEXT SECTION -->

                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <custom type="content" name="notification-banner">
                        <!--========Paste your Content below=================-->

                        <!-- nothing -->

                        <!-- nothing -->

                        <!--BEGIN HELP SECTION -->
                        <table cellspacing="0" cellpadding="0" align="center" border="0" width="80%" bgcolor="#ffffff">
                          <tr>
                            <td valign="top" align="center" width="100%">
                              <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#EFEFF1">
                                <tr>
                                  <td align="center" height="25px" style="background-color: #EFEFF1;">
                                  </td>
                                </tr>
                              </table>
                              <table width="100%" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#EFEFF1" style="max-width: 600px; background-color: #EFEFF1;">
                                <tr>
                                  <td align="center" style="padding: 0px;">
                                    <table align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#EFEFF1">
                                      <tr>
                                        <td align="center" valign="top" style="padding: 25px 25px 25px 25px; background-color: #EFEFF1;">
                                          <img src="https://s3.amazonaws.com/growth.lyft.com/Business/Icons/Module%203_email_icon%402x.png" width="50" border="0" style="display: inline-block; width: 50px; height: auto; outline: none;">
                                        </td>
                                        <td align="left" style="font-family: 'LyftPro-Regular', Arial, Helvetica, sans-serif; font-size: 18px; line-height: 1.4; color: #000000; padding: 15px 15px 15px 0; background-color: #EFEFF1;">
                                          Have a question? <br />
                                          <a href="/cdn-cgi/l/email-protection#d4b6a1a7bdbab1a7a7f9a7a1a4a4bba6a094b8adb2a0fab7bbb9" style="color: #ff00bf;">Reach out to our team</a>
                                        </td>
                                      </tr>
                                    </table>
                                  </td>
                                </tr>
                              </table>
                              <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#EFEFF1">
                                <tr>
                                  <td align="center" height="25px" style="background-color: #EFEFF1;">
                                  </td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </table>

                        <!--END HELP SECTION -->
                        <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
                          <tr>
                            <td align="center" height="50px" style="background-color: #FFFFFF;">
                            </td>
                          </tr>
                        </table>
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->

                      <!-- nothing -->

                      <!--END TEXT SECTION -->
                      <!--=======End your Content here=====================-->

                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-02">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-03">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-04">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-05">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-06">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-07">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-08">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-09">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <table align="center" bgcolor="" border="0" cellpadding="0" cellspacing="0" class="fullScreen" style="width:100% !important;" width="600">
                  <tr>
                    <td bgcolor="" class="" style="width:100% !important; padding: 0;">
                      <!--========Paste your Content below=================-->
                      <custom type="content" name="section-10">
                        <!--=======End your Content here=====================-->
                    </td>
                  </tr>
                </table>

                <!--=================FOOTER=====================-->
                <table align="center" cellpadding="0" cellspacing="0" width="100%" style=" width:100% !important;">
                  <tr>
                    <td align="center" valign="middle" style="padding: 0 25px 0 0;"></td>
                    <td width="100%" align="center" valign="middle" style="border-top: 1px solid #d8d8d8;"></td>
                    <td align="center" valign="middle" style="padding: 0 25px 0 0;"></td>
                  </tr>
                </table>
                <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" class="mobileView" style="width:100% !important;" width="600">
                  <tr>
                    <td>
                      <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" class="mobileView" style="" width="100%">
                        <tr>
                          <td align="left" style="color: #88888f; font-family: 'LyftPro-Regular', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; line-height: 18px; font-weight:normal; padding: 10px 0px 0px 25px;" valign="middle" width="100%">
                            <a class="footerLinks" href="https://help.lyft.com/hc/en-us" style=" text-decoration: none; color: #88888f" target="_blank"><span class="contact">Contact</span></a>
                          </td>
                        </tr>
                        <tr>
                          <td align="left" style="color: #88888f; font-family: 'LyftPro-Regular', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; line-height:18px; font-weight: normal; padding: 10px 0px 0px 25px; text-decoration: none;" valign="middle">
                            185 Berry St, Ste 5000, San Francisco, CA 94107<br/>&#169; 2018 Lyft, Inc.</td>
                        </tr>
                        <!--===========CUSTOMER ACTIONS===========-->
                      </table>
                      <!--=============END CUSTOMER ACTIONS========-->
                    </td>
                  </tr>
                  <tr>
                    <td width="auto" style="display: block;" height="40">&nbsp;</td>
                  </tr>
                </table>
                <!--=================END FOOTER=====================-->

              </td>
            </tr>
          </table>
          <!-- END WHITE PAGE BODY CONTAINER/WRAPPER -->
          <table cellspacing="0" cellpadding="0" align="center" border="0" width="100%" bgcolor="#F3F3F5">
            <tr>
              <td class="divider" align="center" height="16px" style="background-color: #F3F3F5;">
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    <!-- FULL PAGE WIDTH WRAPPER WITH TINT -->

    <!-- McGuyver'ed Android Gmail Spacer Fix -->

    <table border="0" cellpadding="0" cellspacing="0" class="hideDevice">
      <tr>
        <td class="hideDevice" height="1" style="min-width:700px; font-size:0px; line-height:0px;"><img height="1" src="http://image.lyftmail.com/lib/fe6915707166047a7d14/m/8/Spacer+for+Gmail.gif" style="min-width: 700px; text-decoration: none; border: none; -ms-interpolation-mode: bicubic;"></td>
      </tr>
    </table>

    <!--END FIX-->

    <!-- RETURNPATH TRACKING -->
    <table border="0" cellpadding="0" cellspacing="0" align="center">
      <tr>
        <td border="0" align="center" height="1" style="font-size:0px; line-height:0px;">
          <img src="https://pixel.inbox.exacttarget.com/pixel.gif?r=4a4f30aa41389e0aba9e92c56574b86e3fc20465" width="1" height="1" />
          <img src="https://pixel.app.returnpath.net/pixel.gif?r=4a4f30aa41389e0aba9e92c56574b86e3fc20465" width="1" height="1" />
        </td>
      </tr>
    </table>
    <!-- END RETURNPATH  TRACKING -->
    <custom name="opencounter" type="tracking" style="display:none;">
     
      <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script></body>

</html>''';
    final message = Message()
      ..from = Address(username, 'Your name')
      ..recipients.add(email)
      ..subject = 'Your verification code :: 😀 :: ${DateTime.now()}'
      ..text = 'This is the plain text.\nThis is line 2 of the text part.'
      // ..attachments.add(FileAttachment(
      //     File('C:/Users/DELL/Desktop/pim/assets/images/003-tiger.png')))
      ..html =
          yourHtmlTemplate.replaceAll('{{VERIFICATIONCODE}}', verificationcode);

    try {
      final sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent.');
      for (var p in e.problems) {
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
    // DONE

    // Let's send another message using a slightly different syntax:
    //
    // Addresses without a name part can be set directly.
    // For instance `..recipients.add('destination@example.com')`
    // If you want to display a name part you have to create an
    // Address object: `new Address('destination@example.com', 'Display name part')`
    // Creating and adding an Address object without a name part
    // `new Address('destination@example.com')` is equivalent to
    // adding the mail address as `String`.

    // Sending multiple messages with the same connection
    //
    // Create a smtp client that will persist the connection
    var connection = PersistentConnection(smtpServer);

    // Send the first message
    await connection.send(message);

    // send the equivalent message
    // await connection.send(equivalentMessage);

    // close the connection
    await connection.close();
  }

  TextFormField buildConformPassFormField() {
    return TextFormField(
      obscureText: true,
      onSaved: (newValue) => conform_password = newValue,
      onChanged: (value) {
        if (value.isNotEmpty) {
          removeError(error: kPassNullError);
        } else if (value.isNotEmpty && password == conform_password) {
          removeError(error: kMatchPassError);
        }
        conform_password = value;
      },
      validator: (value) {
        if (value.isEmpty) {
          addError(error: kPassNullError);
          return "";
        } else if ((password != value)) {
          addError(error: kMatchPassError);
          return "";
        }
        return null;
      },
      decoration: InputDecoration(
        labelText: tr("Confirm Password"),
        hintText: tr("Re-enter your password"),
        // If  you are using latest version of flutter then lable text and hint text shown like this
        // if you r using flutter less then 1.20.* then maybe this is not working properly
        floatingLabelBehavior: FloatingLabelBehavior.always,
        suffixIcon: CustomSurffixIcon(svgIcon: "assets/icons/Lock.svg"),
      ),
    );
  }

  TextFormField buildPasswordFormField() {
    return TextFormField(
      obscureText: true,
      onSaved: (newValue) => password = newValue,
      onChanged: (value) {
        if (value.isNotEmpty) {
          removeError(error: kPassNullError);
        } else if (value.length >= 8) {
          removeError(error: kShortPassError);
        }
        password = value;
      },
      validator: (value) {
        if (value.isEmpty) {
          addError(error: kPassNullError);
          return "";
        } else if (value.length < 8) {
          addError(error: kShortPassError);
          return "";
        }
        return null;
      },
      decoration: InputDecoration(
        labelText: ("Password"),
        hintText: tr("Enter your password"),
        // If  you are using latest version of flutter then lable text and hint text shown like this
        // if you r using flutter less then 1.20.* then maybe this is not working properly
        floatingLabelBehavior: FloatingLabelBehavior.always,
        suffixIcon: CustomSurffixIcon(svgIcon: "assets/icons/Lock.svg"),
      ),
    );
  }

  TextFormField buildEmailFormField() {
    return TextFormField(
      keyboardType: TextInputType.emailAddress,
      onSaved: (newValue) => email = newValue,
      onChanged: (value) {
        if (value.isNotEmpty) {
          removeError(error: kEmailNullError);
        } else if (emailValidatorRegExp.hasMatch(value)) {
          removeError(error: kInvalidEmailError);
          email = value;
        }
        return null;
      },
      validator: (value) {
        if (value.isEmpty) {
          addError(error: kEmailNullError);
          return "";
        } else if (!emailValidatorRegExp.hasMatch(value)) {
          addError(error: kInvalidEmailError);
          return "";
        }
        return null;
      },
      decoration: InputDecoration(
        labelText: "Email",
        hintText: tr("Enter your email"),
        // If  you are using latest version of flutter then lable text and hint text shown like this
        // if you r using flutter less then 1.20.* then maybe this is not working properly
        floatingLabelBehavior: FloatingLabelBehavior.always,
        suffixIcon: CustomSurffixIcon(svgIcon: "assets/icons/Mail.svg"),
      ),
    );
  }
}
